### PR TITLE
BaseImage: Detect if frame is new or not to avoid wasted update cycles

### PR DESCRIPTION
**Pull request by nickdevereaux**

### CODE REVIEW

**Comment by elliotwoods** [comment]
`isFrameNew` vs `IsFrameNew()` is awkward

`getIsFrameNew()` could be acceptable, but the oF standard is `isFrameNew()` so i suggest renaming the bool flag to `isFrameNewFlag`

**Comment by nickdevereaux** [comment]
Sure can do. Coming from a C# background sorry! Used to accepting all the Resharper suggestions to clear out all the squiggly lines ;) Still learning the C++ naming convention ropes.

**Comment by mattfelsen** [comment]
This looks really useful! Is this just a style change that's preventing this from being merged? If so I'm happy to update & submit a new PR. I'm not around a Windows machine at the moment so I can't test if this is actually functional :smile:

**Comment by elliotwoods** [comment]
ah, forgot about this one.
yes it's just the styling
happy to test here if you edit the PR

**Comment by mattfelsen** [comment]
This can be closed with the merging of https://github.com/elliotwoods/ofxKinectForWindows2/pull/38

**Comment by elliotwoods** [comment]
thanks!

**Pull request closed without merging**
