### PR TITLE
Add BaseImage::isFrameNew()

### PR DESCRIPTION
**Pull request by mattfelsen**
A replacement for https://github.com/elliotwoods/ofxKinectForWindows2/pull/31 with fixes to code style. Thanks to @nickdevereaux for the original work! New variable/method names are based on the usage in ofxKinect.

I also changed lastFrameTime from INT64 to long based on your comments here https://github.com/elliotwoods/ofxKinectForWindows2/pull/32#discussion_r30300894.

I did minimal testing here but it looks functional. kinect.getDepthSource()->isFrameNew() is returning true every other frame for an app running at 60fps.

### CODE REVIEW

**Comment by nickdevereaux** [comment]
Thanks @mattfelsen! I've been so busy I haven't had a chance to make the changes. I also have a whole bunch of updates for fixing mesh speed in the depth source, face source, and a few other things I'll need to tidy up and for a PR in the next few weeks. Thanks again for covering for me :smiley:

**Comment by mattfelsen** [comment]
:wink: :+1:

**Comment by elliotwoods** [comment]
looks good!
thanks

**Comment by mattfelsen** [comment]
Would you mind cherry-picking this into 0.8.4 as well?

**Comment by mattfelsen** [comment]
(Let me know if you prefer a separate PR?)

**Pull request merged**
