### PR TITLE
Added body index example.

### PR DESCRIPTION
**Pull request by prisonerjohn**
Added an example where all vertices not belonging to a body are discarded. This is done in a shader by checking the color in the bodyIndex texture.

### CODE REVIEW

**Comment by elliotwoods** [comment]
i think the shaders have been ignored since they're in the data folder
could you force add them?

**Comment by prisonerjohn** [comment]
Oops, here they are.

**Comment by elliotwoods** [comment]
sounds good to me!
just one final thing to check
you're PR'ing against the master branch (009)
whilst only 0.8.4 is currently 'officially' supported
can you confirm that you're using oF 009 and this addon is working for you?
(means you are on 32bit?)

**Comment by prisonerjohn** [comment]
Cool! Yep, it's working off the master OF branch.

**Comment by elliotwoods** [comment]
thanks!

**Pull request merged**
